# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9254fa86c3b6dd113f0aa58c908c548475dabbb1991e44bfd63355540a0233f9e3cc89b0cfb600b76eeffd399452731ba339790d6adcda5b5d021e661ccfaed

test:
  secret_key_base: e5e6718ac5a30008d3c1112889cdaa58b8ee44325dffcfc48375f392e4a0523461dac186e0cdd0da5757f44b435a986f8654966646d357fb4b15616db102b2e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
